version: '3.8'
services:
    application:
        container_name: anime_collection_php
        build: 
            context: ./docker
            dockerfile: Dockerfile
        working_dir: /var/www
        command: php-fpm
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - anime-collection-network

    nginx:
        image: nginx:alpine
        container_name: anime_collection_nginx
        ports:
            - "9000:80"
            - "444:443"
        volumes:
            - ./:/var/www/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./docker/nginx/ssl/:/etc/ssl
        networks:
        - anime-collection-network

    database:
        image: postgres:13-alpine
        container_name: anime_collection_database
        environment:
            POSTGRES_DB: app
            POSTGRES_PASSWORD: ChangeMe
            POSTGRES_USER: symfony
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            - "5432"
        networks:
            - anime-collection-network

networks:
    anime-collection-network:
        driver: bridge

volumes:
    db-data:
        driver: local
