version: '3.8'
services:
    # PHP Service
    application:
        container_name: application
        build: 
            context: ./docker
            dockerfile: Dockerfile
        ports:
            - "9000:8000"
        environment:
            SERVICE_NAME: application
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app-network


    #Nginx Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - ./:/var/www/
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./docker/nginx/ssl/:/etc/ssl
        networks:
        - app-network


    #PostgreSQL Service
    database:
        image: postgres:13-alpine
        container_name: database
        environment:
            POSTGRES_DB: app
            POSTGRES_PASSWORD: ChangeMe
            POSTGRES_USER: symfony
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            - "5432"
        networks:
            - app-network


    # Mail catcher Service
    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]

        
#Docker Networks
networks:
    app-network:
        driver: bridge

#Volumes
volumes:
    db-data:
        driver: local
